name: Build
on:
  push:
    branches: [ nextgen, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - run: chmod +x gradlew

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew build -x test -x detekt --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: liquidbounce
          path: build/libs/*.jar
          retention-days: 90
